### ISSUE TITLE
Conflicting issue with lsp_signature.nvim

### ISSUE THREAD

**Issue by vsedov** [quangnguyen30192/cmp-nvim-ultisnips#13] opened 2021-10-09 13:28 UTC
Issue with ray-x/lsp_signature.nvim and cmp-nvim-utilsnips - on lsp_signature.nvim when you set floating_window = true, the snippets does not forward with tab shown when you call 
```
 return press("<C-R>=UltiSnips#ExpandSnippet()<CR>")
```

though im not completely sure what's causing this.

Working example without the float
https://vimeo.com/627416002

Not working, with the float :
https://vimeo.com/627417127

**Comment by anstadnik** [comment] 2021-10-11 05:45
I've just checked, and for me everything works. I use ray-x/lsp_signature.nvim, and with both `floating_window = true` and `floating_window = false` I can jump back and forth inside the snippet. Could you provide a minimal `init.nvim`?

**Comment by quangnguyen30192** [comment] 2021-11-25 04:15
@vsedov  sorry for the late response, does the plugin work for you now?

**Comment by vsedov** [comment] 2021-11-25 13:51
Nah all good, I should have closed this issue, sorry about that. Everything is working now : ) .

**Comment by ranebrown** [comment] 2021-12-19 15:18
What was the solution? I'm seeing the same problem when using lsp_signature floating window.

**Comment by quangnguyen30192** [comment] 2021-12-19 16:00
Could you check the following?
> I've just checked, and for me everything works. I use ray-x/lsp_signature.nvim, and with both floating_window = true and floating_window = false I can jump back and forth inside the snippet. Could you provide a minimal init.nvim?

**Comment by vsedov** [comment] 2021-12-19 16:09
> What was the solution? I'm seeing the same problem when using lsp_signature floating window.

Hmm truth be told i have forgotten what i did, If I'm not mistaken it was how lsp sig was being called, if you are directly using a cfg or not, and if its within the attach function in your lsp config . 

Another thing id checks if its being called through opt or  not.

**Comment by ranebrown** [comment] 2021-12-19 18:34
Here is a minimal config. I was testing using clangd (`:LspInstall clangd`) after the initial `nvim -u minimal_config.lua`. Expanding the lsp provided snippet for the sum function makes it so you can't jump between the tab stops. Setting lsp_signtature floating window to false makes it work as expected.

<details>
  <summary>Minimal init</summary>

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"

local function load_plugins()
    require("packer").startup({
        function(use)
            use({ "wbthomason/packer.nvim" })
            use({ "SirVer/ultisnips" })
            use({
                "hrsh7th/nvim-cmp",
                requires = {
                    "hrsh7th/cmp-nvim-lsp",
                    "quangnguyen30192/cmp-nvim-ultisnips",
                },
                config = function()
                    local cmp = require("cmp")
                    local cmp_ultisnips_mappings = require(
                        "cmp_nvim_ultisnips.mappings"
                    )

                    cmp.setup({
                        snippet = {
                            expand = function(args)
                                vim.fn["UltiSnips#Anon"](args.body)
                            end,
                        },
                        mapping = {
                            ["<Tab>"] = cmp.mapping(function(fallback)
                                cmp_ultisnips_mappings.compose({
                                    "jump_forwards",
                                    "select_next_item",
                                })(fallback)
                            end, {
                                "i",
                                "s",
                                "c",
                            }),
                            ["<S-Tab>"] = cmp.mapping(function(fallback)
                                cmp_ultisnips_mappings.compose({
                                    "jump_backwards",
                                    "select_prev_item",
                                })(fallback)
                            end, {
                                "i",
                                "s",
                                "c",
                            }),
                        },
                        sources = {
                            { name = "nvim_lsp", priority = 100, group_index = 1 },
                            { name = "ultisnips", priority = 80, group_index = 1 },
                        },
                    })
                end,
            })
            use({
                "nvim-treesitter/nvim-treesitter",
                config = function()
                    require("nvim-treesitter.configs").setup({
                        ensure_installed = {"cpp" },
                        highlight = { enable = true },
                    })
                end,
                run = ":TSUpdate",
            })
            use({ "williamboman/nvim-lsp-installer" })
            use({
                "neovim/nvim-lspconfig",
                config = function()
                    local on_attach = function(client)
                        if client.resolved_capabilities.signature_help then
                            require("lsp_signature").on_attach({
                                floating_window = true,
                                hint_enable = false,
                                hi_parameter = "IncSearch",
                            })
                        end
                    end

                    local function make_config()
                        local capabilities = vim.lsp.protocol.make_client_capabilities()
                        capabilities = require("cmp_nvim_lsp").update_capabilities(
                            capabilities
                        )
                        return {
                            capabilities = capabilities,
                            on_attach = on_attach,
                        }
                    end
                    local lsp_installer = require("nvim-lsp-installer")
                    local lsp_installer_path = "/tmp/nvim/lsp_servers/"
                    lsp_installer.settings({
                        install_root_dir = lsp_installer_path,
                    })

                    lsp_installer.on_server_ready(function(server)
                        local default_opts = make_config()

                        -- server specific options
                        local server_opts = {
                            ["clangd"] = function()
                                local custom_opts = make_config()
                                custom_opts.cmd = {
                                    lsp_installer_path .. "/clangd/clangd",
                                    "--background-index",
                                    "--clang-tidy",
                                }
                                return custom_opts
                            end,
                        }

                        -- call server setup (equivalent to lspconfig's setup function)
                        server:setup(
                            server_opts[server.name] and server_opts[server.name]()
                                or default_opts
                        )
                        vim.cmd([[ do User LspAttachBuffers ]])
                        vim.diagnostic.config({
                            underline = false,
                            virtual_text = false,
                            signs = true,
                            update_in_insert = false,
                            float = { border = "rounded" },
                        })
                    end)
                end,
            })
            use({ "ray-x/lsp_signature.nvim" })
        end,
        config = {
            package_root = package_root,
            compile_path = install_path .. "/plugin/packer_compiled.lua",
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({
        "git",
        "clone",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```
</details>

<details>
  <summary>Test file</summary>

```cpp  
#include <iostream>

auto sum(int a, int b) -> int
{
    return a+b;
}

auto main(int argc, char *argv[]) -> int
{

    return 0;
}
```
</details>

**Comment by smjonas** [comment] 2021-12-19 21:47
@ranebrown I can't reproduce your issue using your config (I am able to jump to the next / previous tabstop normally). What are the necessary steps to reproduce your issue and what is the expected behaviour?

**Comment by ranebrown** [comment] 2021-12-19 21:59
1. Save above files as `minimal_init.lua` and `test.cpp`
2. `nvim -u minimal_init.lua` after packer install run `:LspInstall clangd`
3. quit
4. `nvim -u minimal_init.lua test.cpp`
5. Go to main function and start typing `sum` select LSP snippet for `sum()` from cmp menu and expand with `C-y`
6. Type `1` for first argument. Hit tab to go to next argument and it inserts a literal tab.

Expected behavior is to jump to the second argument position while showing the lsp signature floating window. The jumping works correctly if lsp signature floating window is disabled.

**Comment by smjonas** [comment] 2021-12-19 22:03
Thanks for your reproduction steps, could reproduce it now.

**Comment by smjonas** [comment] 2021-12-19 22:26
I don't think this is related to `cmp-nvim-ultisnips` since it also happens with this config (I removed the mappings and plugin). Closing for now.
<details>
  <summary>Minimal config</summary>

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"

local function load_plugins()
    require("packer").startup({
        function(use)
            use({ "wbthomason/packer.nvim" })
            use({ "SirVer/ultisnips" })
            use({
                "hrsh7th/nvim-cmp",
                requires = {
                    "hrsh7th/cmp-nvim-lsp",
                },
                config = function()
                    local cmp = require("cmp")

                    cmp.setup({
                        snippet = {
                            expand = function(args)
                                vim.fn["UltiSnips#Anon"](args.body)
                            end,
                        },
                        sources = {
                            { name = "nvim_lsp", priority = 100, group_index = 1 },
                        },
                    })
                end,
            })
            use({
                "nvim-treesitter/nvim-treesitter",
                config = function()
                    require("nvim-treesitter.configs").setup({
                        ensure_installed = {"cpp" },
                        highlight = { enable = true },
                    })
                end,
                run = ":TSUpdate",
            })
            use({ "williamboman/nvim-lsp-installer" })
            use({
                "neovim/nvim-lspconfig",
                config = function()
                    local on_attach = function(client)
                        if client.resolved_capabilities.signature_help then
                            require("lsp_signature").on_attach({
                                floating_window = true,
                                hint_enable = false,
                                hi_parameter = "IncSearch",
                            })
                        end
                    end

                    local function make_config()
                        local capabilities = vim.lsp.protocol.make_client_capabilities()
                        capabilities = require("cmp_nvim_lsp").update_capabilities(
                            capabilities
                        )
                        return {
                            capabilities = capabilities,
                            on_attach = on_attach,
                        }
                    end
                    local lsp_installer = require("nvim-lsp-installer")
                    local lsp_installer_path = "/tmp/nvim/lsp_servers/"
                    lsp_installer.settings({
                        install_root_dir = lsp_installer_path,
                    })

                    lsp_installer.on_server_ready(function(server)
                        local default_opts = make_config()

                        -- server specific options
                        local server_opts = {
                            ["clangd"] = function()
                                local custom_opts = make_config()
                                custom_opts.cmd = {
                                    lsp_installer_path .. "/clangd/clangd",
                                    "--background-index",
                                    "--clang-tidy",
                                }
                                return custom_opts
                            end,
                        }

                        -- call server setup (equivalent to lspconfig's setup function)
                        server:setup(
                            server_opts[server.name] and server_opts[server.name]()
                                or default_opts
                        )
                        vim.cmd([[ do User LspAttachBuffers ]])
                        vim.diagnostic.config({
                            underline = false,
                            virtual_text = false,
                            signs = true,
                            update_in_insert = false,
                            float = { border = "rounded" },
                        })
                    end)
                end,
            })
            use {
              "ray-x/lsp_signature.nvim",
              config = function()
                require"lsp_signature".setup {
                  floating_window = false,
                }
              end
            }
        end,
        config = {
            package_root = package_root,
            compile_path = install_path .. "/plugin/packer_compiled.lua",
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({
        "git",
        "clone",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```
</details>

**Closed by smjonas** 2021-12-19 22:26 UTC
Labels: bug, mappings

**Comment by ranebrown** [comment] 2021-12-20 12:38
Fair enough. Thanks for taking a look.
