### ISSUE TITLE
Error detected while processing TextChangedI Autocommands for "*":

### ISSUE THREAD

**Issue by SingularisArt** [quangnguyen30192/cmp-nvim-ultisnips#85] opened 2023-01-10 03:42 UTC
When I open a latex file and start typing, I get the following issue:

```
Error detected while processing TextChangedI Autocommands for "*":                                                                                   
Error executing lua callback: Vim(return):Error invoking 'python_execute' on channel 5 (python3-script-host):                                        
Traceback (most recent call last):                                                                                                                   
  File "<string>", line 19, in <module>                                                                                                              
TypeError: SnippetDefinition._context_match() takes 2 positional arguments but 3 were given                                                          
stack traceback:                                                                                                                                     
        [C]: in function 'load_snippets'                                                                                                             
        ...azy/cmp-nvim-ultisnips/lua/cmp_nvim_ultisnips/source.lua:27: in function 'complete'                                                       
        ...laris/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:296: in function 'complete'                                                      
        ...gularis/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:286: in function 'complete'                                                      
        ...gularis/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:168: in function 'callback'                                                      
        ...gularis/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:218: in function 'autoindent'                                                    
        ...gularis/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:160: in function 'on_change'                                                     
        ...gularis/.local/share/nvim/lazy/nvim-cmp/lua/cmp/init.lua:301: in function 'callback'                                                      
        ...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'                                                           
        ...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
```

I've got vimtex installed, and when I disable vimtex, this error goes away. Could you look more into this to see if you can fix it because I would like to have both plugins without one causing an error to the other.

**Comment by quangnguyen30192** [comment] 2023-01-10 04:22
Thank you for reporting. I will check it soon

**Comment by quangnguyen30192** [comment] 2023-01-11 03:24
As your plugin manager is fixed, could you try again to see if it still happens?

**Comment by SingularisArt** [comment] 2023-01-11 03:25
I still get the same issue. I think it has something to do with an autocmd command or something that's conflicting with vimtex.

**Comment by smjonas** [comment] 2023-01-11 16:39
Duplicate of #80.

**Closed by smjonas** 2023-01-11 16:39 UTC
Labels: duplicate
